name: generative-journey
channels:
  - pyro
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - jupyterlab
  - ipykernel
  - matplotlib
  - tqdm
  - arviz
  - scipy
  - pyro-ppl
  - pip:
#    - torch
    - scikit-learn
    - imageio
    - pytest
    - pytest-cov
    - pre-commit
    - -e .          # install src package in editable mode

# Set environment variables
variables:
  KMP_DUPLICATE_LIB_OK: TRUE
